### ISSUE TITLE
Instability with linux-manjaro-14.0

### ISSUE THREAD

**Issue by user18130814200115-2** [SvenKiljan/archlinuxarm-pbp#10]
With the latest kernel, the system boots up fine but the power led stays on orange.
After 10-15 minutes, the laptop crashes and the power led flashes green-orange indicating a kernel panic.

If this is an issue others experience too (and it is not simply my configuration), then the repo should probably stay on 13.5 for the time being.

**Comment by erer1243** [comment]
I am experiencing the same issues

**Comment by justinesmithies** [comment]
I experienced the same issues as above too.

**Comment by SvenKiljan** [comment]
Just upgraded my system to  5.14.1-1-MANJARO-ARM, which was released today for Arch Linux ARM on Pinebook Pro. The power LED is green after the boot loader (Tow-Boot) finishes doing its thing, and the uptime is now 20 minutes without issue.

Please re-test after upgrading. If the issue still occurs, please specify which boot loader is used.

**Comment by justinesmithies** [comment]
I've recently updated too and it's been running for 1hr30 without issue so far. Hopefully that's it resolved.

**Comment by user18130814200115-2** [comment]
Stability is back to normal in the new version.
Closing as this issue is no longer relevant.
