### ISSUE TITLE
Freezing randomly

### ISSUE THREAD

**Issue by justinesmithies** [SvenKiljan/archlinuxarm-pbp#11]
With regards to the last issue my pbp still freezes although less. I've been using it solid today running sway too and since 7am here it's now 18:45 it's frozen twice. Everything just stops no keys or mouse and power led is solid green. Only way out is to power cycle. Oh and it's fully charged too. Not sure yet what is causing this ?

**Comment by SvenKiljan** [comment]
My Pinebook Pro uses sway, and currently has an uptime of more than 36 hours. Your problem is probably not distribution specific, but likely related to a hardware issue. Test other distributions, and ask for help in the PINE64 forum if necessary.
