### ISSUE TITLE
Package mirror is unavailable

### ISSUE THREAD

**Issue by SvenKiljan** [SvenKiljan/archlinuxarm-pbp#12]
The current package mirror is unavailable. This is being worked on, and will be fixed as soon as possible.

**Comment by dukla2000** [comment]
Is this the cause of pacman barfing "failed retrieving file 'archlinuxarm-pbp.db' from pacman.kiljan.org"?
If so, all strength to your arm.

**Comment by SvenKiljan** [comment]
Confirmed that the mirror is available again. It took a while to confirm it, since I had to properly test it.

**Comment by SvenKiljan** [comment]
Mirror still has some issues. Reopening for now.

**Comment by SvenKiljan** [comment]
Updates are now handled properly.
