### ISSUE TITLE
wlan0 wifi interface not detected on boot

### ISSUE THREAD

**Issue by mmausler** [SvenKiljan/archlinuxarm-pbp#14]
Hello,

I have followed the install guide for installing to a microSD card, and am able to boot into an Arch Linux ARM system. However my wifi card is not being recognized. `ip link` will only return the `lo` interface and `wifi-menu` returns `Invalid interface specification`. I am performing the SD install from the default Manjaro installation on the eMMC module. I've tried updating the `ap6256-firmware` package while chrooted into the installation from Manjaro, but it didn't help. `wifi-menu` is able to find the interface while I'm chrooted into the install, its just when I boot from it that its not available.  Any assistance or pointers you could provide would be appreciated.

Thank you

**Comment by mkellyxp** [comment]
Just wanted to come here and say this is what’s happening to me too. 

I can boot to an sd with armbian so I know that the privacy switch isn’t the issue. 

When I run “ip a” it just doesn’t show wlan0 at all. Like it’s not there. 

I was able to hook up a usb wifi adapter and updated and rebooted.  But still, nothing.

**Comment by SvenKiljan** [comment]
I have trouble reproducing the issue. Could you attach the output of `dmesg` of a fresh Arch Linux ARM installation?

**Comment by BenKing6** [comment]
Hi, I have a Aug 2022 Pinebook Pro too, and I'm having the same issue. Wifi is working fine on Manjaro from eMMC and SD, as well as PMOS from SD. I've attached a copy of my dmesg from my Arch install on eMMC, as requested.

[dmesg.txt](https://github.com/SvenKiljan/archlinuxarm-pbp/files/9472049/dmesg.txt)

**Comment by SvenKiljan** [comment]
Relevant dmesg lines:
```
[   23.514522] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   23.516094] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.pine64,pinebook-pro.bin failed with error -2
[   23.519876] usbcore: registered new interface driver brcmfmac
[   23.524606] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.pine64,pinebook-pro.txt failed with error -2
[   23.524678] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.txt failed with error -2
```

Line 2 is not interesting. A Pinebook Pro with a working wireless card has the same error. It is not critical that a .bin file with the exact model name of the device in the filename is missing. Line 5 and 6 are far more interesting. The missing text file concerns configuration parameters for the wireless card. Indeed, this text file seems to be missing from the latest install image, preventing wireless from being used on newer Pinebook Pro models.

Interesting to note is that my Pinebook Pro (older model) has and uses brcmfmac43456-sdio.pine64,pinebook-pro.txt. Note the last digit being a 6 and not a 5.

It can all be traced back to [this](https://lore.kernel.org/all/20220614141249.3975556-2-pbrobinson@gmail.com/).

> This is the refresh of the Pinebook Pro, the first rev has a Synaptics brcmfmac part which the vendor doesn't provide firmware.

So in other words, a new firmware configuration must be included and linked.

I updated a fresh Arch Linux ARM installation, and /usr/lib/firmware/brcm/brcmfmac43455-sdio.pine64,pinebook-pro.txt is now included.

@mmausler 
You tried updating ap6256-firmware manually. However, the files for brcmfmac43455 seem to be included in (newer) linux-firmware packages. That explains why your manual update did nothing.

@BenKing6 
Can you provide an internet connection to your Pinebook Pro in a different way (e.g. a USB Ethernet or wireless adapter, WiFi tethering over USB using an Android phone, ...), update your system, reboot, and test if the wireless internal network card works? Also, please confirm if /usr/lib/firmware/brcm/brcmfmac43455-sdio.pine64,pinebook-pro.txt exists. If it does, all I need to do is to prepare a fresh installation image so solve this issue.

**Comment by BenKing6** [comment]
I've done a system update via USB-C dock with ethernet, and now the wifi adapter is detected and working, and I'm writing this reply wirelessly. I've checked and both `brcmfmac43455-sdio.pine64,pinebook-pro.txt` and `brcmfmac43456-sdio.pine64,pinebook-pro.txt` are in `/usr/lib/firmware/brcm/` on my machine now. 

Thanks for the speedy fix :)

**Comment by SvenKiljan** [comment]
A new root filesystem has been released that has the new files included. I verified that the new filesystem contains the required configuration file for the wireless network interface of newer Pinebook Pro models. For reference, the wireless chipsets:

Old models: AP6256 (before mid-2022-ish)
New models: AW-CM256SM (after mid-2022-ish)

**Comment by AeroNotix** [comment]
Just upgraded, wifi card not visible after reboot. I have both the files listed above. What can I do?

**Comment by SvenKiljan** [comment]
@AeroNotix 

- Create a new issue. This issue is related to the presence of a new wireless network interface in newer PBP models. Your issue is different.
- In your new issue, add as much information as possible. Think of full `dmesg` output after boot, ideally from before the update and from after the update for comparsion.
