### ISSUE TITLE
Provide Flashable Images

### ISSUE THREAD

**Issue by UltraBlackLinux** [SvenKiljan/archlinuxarm-pbp#17]
Hey there,
I was wondering if you could add flashable images to this repo. I really like the work you have done, though I need a flashable image, just because I'm not really familiar with the process of installing arch, even if it's documented like that.
Furthermore, I like having a simple way of reinstalling my system, in this case via a flashable image. If I were to create a disk image of a finished installation I would be left with a 130G file. Compressing it would be equally as bad as read-write-speeds are a huge limiting factor.
Is this possible? Manjaro has really let me down a few times in the recent past. I would like to continue going arch based, just without manjaro.
Thanks!

**Comment by SvenKiljan** [comment]
The installation instructions in this repository are based on the installation instructions of Arch Linux ARM, adjusted for the Pinebook Pro. Anybody who is familiar with installing Arch Linux (ARM) will be able to use this repository.

Disk images are not the Arch Linux (ARM) [way](https://wiki.archlinux.org/title/Arch_Linux#User_centrality). If you need a disk image, it is likely that another distribution will be a better match for you.

**Comment by UltraBlackLinux** [comment]
Hm, I see. Thanks!
