### ISSUE TITLE
RAM getting full in xorg (panfrost)?

### ISSUE THREAD

**Issue by petersen77** [SvenKiljan/archlinuxarm-pbp#18]
Hi.

After installing Xorg & xfce4 the RAM usage is rising without any open windows until it hits 4GB. Afterwards Arch crashes back to console, restating Xorg results in the same behaviour.

Thank you in advance.

**Comment by SvenKiljan** [comment]
This is most likely not specific to Arch Linux ARM on Pinebook Pro. Test this (on Arch Linux ARM-supported hardware) and take it upstream if necessary.
