### ISSUE TITLE
Upcoming breaking changes with Tow-Boot 002

### ISSUE THREAD

**Issue by samueldr** [SvenKiljan/archlinuxarm-pbp#5]
Hi,

There are a couple breaking changes in the upcoming release, but the main one, *as far as your documentation goes*, is that the file names in the release tarballs have changed.

 - https://github.com/Tow-Boot/Tow-Boot/commit/bda4db37875cf7249b0e8d17acedf50eeddf1ba3#diff-20f50d9d8d5d6c059b87ad66fbc5df26d9fc46251763547ca9bdcc75564a4368

Additionally, I'm not releasing "intermediary build products" anymore. So *if you still wanted to recommend installing as you are right now* (see #4) it'll be just one file to flash to that first offset. `binaries/Tow-Boot.noenv.bin` in this case, at LBA64 as usual.

But really I recommend not installing "blindly" into the disk, without a protective partition.

**Comment by SvenKiljan** [comment]
I'll leave this issue open to handle later, but note that the main discussion is in #4.

**Comment by SvenKiljan** [comment]
A new package for Tow-Boot is available. The installation instructions will be updated once a new root filesystem is released.

**Comment by SvenKiljan** [comment]
A new root filesystem was released and installation instructions were updated. This solves this issue.
