### ISSUE TITLE
Add instructions for encryption.

### ISSUE THREAD

**Issue by jonascant** [SvenKiljan/archlinuxarm-pbp#8]
Would it be possible to do that? I am not happy to run an unencrypted mobile device as a daily driver.
Thank you!

**Comment by SvenKiljan** [comment]
Encrypted boot is not something Pinebook Pro specific. What one uses Arch Linux ARM for falls outside of the scope of this repository if is not Pinebook Pro related.

Resources that might help you:
https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LUKS_on_a_partition
https://ryankozak.com/luks-encrypted-arch-linux-on-pinebook-pro-again/

I managed to encrypt my own system by following the standard Arch Linux method from the first link. The second link has instructions that were tested specifically with Arch Linux ARM on Pinebook Pro.
