### ISSUE TITLE
Black screen after reboot 

### ISSUE THREAD

**Issue by hellojaccc** [SvenKiljan/archlinuxarm-pbp#9]
64GB eMMC, installed endeavouros kde on arch arm.

When i make system switches(such as upgrading kernel), and reboot by plasma menu, it randomly shows black screen.

- Ctrl + Alt + F2 doesn''t work
- Green LED light
- Fixed by rebooting with power button

**Comment by SvenKiljan** [comment]
@hellojaccc 

Why do you think that this is specific to Arch Linux ARM on Pinebook Pro? As in, the distribution provided in this repository?

**Comment by hellojaccc** [comment]
Yes, arch arm provided in this repository. Installed endeavouros by script installer. 

It never happend with another distro though. I'll check with manjaro tomorrow.
Am i only one with this issue?

**Comment by SvenKiljan** [comment]
> Installed endeavouros by script installer.
> It never happend with another distro though.

Have you tried this on Arch Linux ARM on an [officially supported device](https://archlinuxarm.org/platforms)? If yes and it works on there, feel free to open a new issue. However, you are probably better helped in the [EndeavourOS forum](https://forum.endeavouros.com/). This place is not for general Arch Linux ARM support, neither for EndeavourOS support.
